# Notebook to illustrate some projective geometry math

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

Lets's define some dummy camera matrix K

In [3]:
# let's assume that e are using a camera frame of resolution: 640 x 480
# let's assume there is no skew and fx == fy
K = np.array([
    [500.0, 0.0,   640.0 / 2.0],
    [0.0,   500.0, 480.0 / 2.0],
    [0.0,   0.0,   1.0],
])

print(f'Camera intrinsic matrix K:\n{K}')

Camera intrinsic matrix K:
[[500.   0. 320.]
 [  0. 500. 240.]
 [  0.   0.   1.]]


Let's define some dummy points coordinates in the CCS

In [42]:
# point right in front of the camera (along camera focal axis)
point1_ccs = np.array([0.0, 0.0, 100.0])

# point slightly below camera focal axis
point2_ccs = np.array([0.0, 25.0, 100.0])

# point slightly above camera focal axis
point3_ccs = np.array([0.0, -25.0, 100.0])

Let's see where those points get projected on the camera frame, by using the following equation:

$$ \begin{bmatrix}
				x \\
				y \\
				w
		\end{bmatrix}  =
		\begin{bmatrix}
				f_x & 0 & c_x\\
				0 & f_y & c_y \\
				0 & 0 & 1
			\end{bmatrix}
			\begin{bmatrix}
				X_c \\
				Y_c \\
				Z_c
			\end{bmatrix}
	 $$

In [43]:
pixel1 = K @ point1_ccs
pixel1 /= pixel1[2]
pixel1 = pixel1[:2]

print(f'Projection of 1st point on camera frame: {pixel1}')

pixel2 = K @ point2_ccs
pixel2 /= pixel2[2]
pixel2 = pixel2[:2]

print(f'Projection of 2nd point on camera frame: {pixel2}')

pixel3 = K @ point3_ccs
pixel3 /= pixel3[2]
pixel3 = pixel3[:2]

print(f'Projection of 3rd point on camera frame: {pixel3}')

Projection of 1st point on camera frame: [320. 240.]
Projection of 2nd point on camera frame: [320. 365.]
Projection of 3rd point on camera frame: [320. 115.]


Let's assume a simple case of having a WCS just in front of the CCS (no rotation, just translation along Z)

In [24]:
# no rotation
R = np.eye(3)

print(f'Rotation matrix R:\n{R}')

# translation along Z axis
t = np.array([[0.0], [0.0], [100.0]])

print(f'Translation vector t:\n{t}')

Rotation matrix R:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Translation vector t:
[[  0.]
 [  0.]
 [100.]]


In [28]:
Rt = np.hstack((R, t))

print(f'[R | t] matrix:\n{Rt}')

[R | t] matrix:
[[  1.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [  0.   0.   1. 100.]]


Let's define some dummy points in WCS

In [31]:
# point right in front of the camera (along camera focal axis)
point1_wcs = np.array([0.0, 0.0, 0.0, 1.0])

# point slightly below camera focal axis
point2_wcs = np.array([0.0, 25.0, 0.0, 1.0])

# point slightly above camera focal axis
point3_wcs = np.array([0.0, -25.0, 0.0, 1.0])

Let's see where those points get projected on the camera frame, by using the following equation:

$$ \begin{bmatrix}
				x \\
				y \\
				w
		\end{bmatrix}  =
		\begin{bmatrix}
				f_x & 0 & c_x\\
				0 & f_y & c_y \\
				0 & 0 & 1
			\end{bmatrix}
			\begin{bmatrix}
				R | t
			\end{bmatrix}
			\begin{bmatrix}
				X_c \\
				Y_c \\
				Z_c \\
				1
			\end{bmatrix}
	 $$

In [44]:
pixel4 = K @ Rt @ point1_wcs
pixel4 /= pixel4[2]
pixel4 = pixel4[:2]

print(f'Projection of 1st point on camera frame: {pixel4}')

pixel5 = K @ Rt @ point2_wcs
pixel5 /= pixel5[2]
pixel5 = pixel5[:2]

print(f'Projection of 2nd point on camera frame: {pixel5}')

pixel6 = K @ Rt @ point3_wcs
pixel6 /= pixel6[2]
pixel6 = pixel6[:2]

print(f'Projection of 2nd point on camera frame: {pixel6}')


Projection of 1st point on camera frame: [320. 240.]
Projection of 2nd point on camera frame: [320. 365.]
Projection of 2nd point on camera frame: [320. 115.]


Matrix P:

$$
	P = \begin{bmatrix}
				f_x & 0 & c_x\\
				0 & f_y & c_y \\
				0 & 0 & 1
			\end{bmatrix}
			\begin{bmatrix}
				R | t
			\end{bmatrix}

$$

is often called camera projection matrix


In [35]:
P = K @ Rt
print(P.shape)

(3, 4)
